volumes:
  fake-cht-postgres-data:

services:
  fake-cht:
    image: node:lts-alpine
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./development/fake-cht:/home/node/app
    networks:
      - cht-watchdog-net
    command: >
      sh -c "npm install &&
             npm start"

  fake-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cht
      POSTGRES_USER: cht_couch2pg
      POSTGRES_PASSWORD: cht_couch2pg_password
    volumes:
      - fake-cht-postgres-data:/var/lib/postgresql/data
    networks:
      - cht-watchdog-net
