{
 "title": "CHT Admin Details",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cht_instance",
    "label": "CHT Instance",
    "query": {
     "query": "query_result(up{job=~\"cht\"})"
    }
   },
   {
    "name": "db_name",
    "query": {
     "query": "cht_couchdb_doc_total{instance=~\"$cht_instance\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "CouchDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Doc Count [$db_name]",
   "type": "timeseries",
   "description": "Total number of docs in the database",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "repeat": "db_name",
   "targets": [
    {
     "expr": "cht_couchdb_doc_total{db=\"$db_name\", instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Doc Conflicts",
   "type": "timeseries",
   "description": "Total number of doc conflicts which need to be resolved manually.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "cht_conflict_count{instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Docs",
   "type": "timeseries",
   "description": "The number of deleted docs in the DB.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "cht_couchdb_doc_del_total{instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Update Sequence",
   "type": "stat",
   "description": "The number of changes in the DB",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cht_couchdb_update_sequence{instance=\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "description": "The fragmentation of the db, lower is better, “1” is no fragmentation.",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "cht_couchdb_fragmentation{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHT Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Server Time",
     "type": "stat",
     "description": "The current server date and time, useful for ensuring the server time is correct.",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_date_current_millis{instance=~\"$cht_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sentinel Backlog",
     "type": "timeseries",
     "description": "Number of changes yet to be processed by Sentinel.",
     "gridPos": { "h": 6, "w": 10, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "changes" } },
     "targets": [
      {
       "expr": "cht_sentinel_backlog_count{instance=~\"$cht_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Users Over Replication Limit",
     "type": "timeseries",
     "description": "Number of users that exceeded the replication limit of documents.",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "users" } },
     "targets": [
      {
       "expr": "cht_replication_limit_count{instance=~\"$cht_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Client Feedback/Errors",
     "type": "timeseries",
     "description": "Number of feedback docs created usually indicative of client side errors.",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "cht_feedback_total{instance=~\"$cht_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound Push Backlog",
     "type": "timeseries",
     "description": "Number of changes yet to be processed by Outbound Push.",
     "gridPos": { "h": 6, "w": 10, "x": 5, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "changes" } },
     "targets": [
      {
       "expr": "cht_outbound_push_backlog_count{instance=~\"$cht_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Monthly Active Users",
     "type": "timeseries",
     "description": "Number of users that have connected to the api in the past month.",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "users" } },
     "targets": [
      {
       "expr": "cht_connected_users_count{instance=\"$cht_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(cht_messaging_outgoing_total{instance=~\"$cht_instance\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Due",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 11, "y": 15 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"due\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Delivered",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 15 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"delivered\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Muted",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 11, "y": 19 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"muted\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 19 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"failed\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Messages - Last 100",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 7, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Muted",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 13, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Final",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 13, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}