{
 "title": "CHT Admin",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# CHT Admin Dashboard\n\nSee the [CHT documentation](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/) for more information about monitoring and alterting!"
   }
  },
  {
   "title": "CHT Version Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "targets": [
    { "expr": "cht_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Growth Rate",
   "type": "timeseries",
   "description": "Rate of creation of docs in the Couch databases.",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "docs/hr" } },
   "targets": [
    {
     "expr": "rate(cht_couchdb_doc_total[1h]) * 60 * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Server Time",
   "type": "stat",
   "description": "The current server date and time, useful for ensuring the server time is correct.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cht_date_current_millis", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CHT Uptime",
   "type": "stat",
   "description": "How long API has been running.\n",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cht_date_uptime_seconds / 60 / 60 / 24",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Conflicts Rate",
   "type": "stat",
   "description": "Rate of creation of doc conflicts which need to be resolved manually.",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "docs/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cht_conflict_count[1h]) * 60 * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Feedback/Error Rate",
   "type": "stat",
   "description": "Number of feedback docs created usually indicative of client side errors.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "docs/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cht_feedback_total[1h]) * 60 * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Time Accurate",
   "type": "stat",
   "description": "Indicates if the CHT server time matches the time of the Grafana server.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(abs(cht_date_current_millis / 1000 - time()))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Push Backlog",
   "type": "gauge",
   "description": "Number of changes yet to be processed by Outbound Push.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cht_outbound_push_backlog_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Backlog",
   "type": "gauge",
   "description": "Number of changes yet to be processed by Sentinel.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cht_sentinel_backlog_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Fragmentation",
   "type": "bargauge",
   "description": "The fragmentation of the db, lower is better, “1” is no fragmentation.",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cht_couchdb_fragmentation", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users Over Replication Limit",
   "type": "gauge",
   "description": "Number of users that exceeded the replication limit of documents.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cht_replication_limit_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Monthly Active Users",
   "type": "stat",
   "description": "Number of users that have connected to the api in the past month. ",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cht_connected_users_count", "legendFormat": "__auto" }
   ]
  }
 ]
}