{
 "title": "CHT Replication",
 "description": "Monitor metrics for replication health",
 "tags": [ "CHT 4.3+" ],
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cht_instance",
    "label": "CHT Instance",
    "query": {
     "query": "query_result(up{job=~\"cht\"})"
    }
   },
   {
    "name": "interval",
    "query": "2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Replication Apdex",
   "type": "stat",
   "description": "A score of 100 means all successful syncs proceeded by the server are fast enough to satisfy user's expectations (the sync completes in less than 3 mins).  When the server takes longer than 3 minutes, users begin to be less satisfied and this ApDex number reduces. Users tolerate syncs which take between 3mins and 6mins. Users are frustrated by sync times over 6mins.  See the <a href='https://en.wikipedia.org/wiki/Apdex'>Apdex Wikipedia article</a> for more details.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n        (   \n                sum(increase(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\",route=~\".*/get-ids\",le=\"180.0\",code=~\"^2..$|^3..$\"}[$__range]))\n                + (\n                        sum(increase(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\",route=~\".*/get-ids\",le=\"360.0\",code=~\"^2..$|^3..$\"}[$__range]))\n                        - sum(increase(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\",route=~\".*/get-ids\",le=\"180.0\",code=~\"^2..$|^3..$\"}[$__range]))\n                ) / 2\n        ) / sum(increase(cht_api_http_request_duration_seconds_count{instance=~\"$cht_instance\",route=~\".*/get-ids\",code=~\"^2..$|^3..$\"}[$__range]))\n) * 100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "Replication Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cht_api_http_request_duration_seconds_count{instance=~\"$cht_instance\",route=~\".*/get-ids\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t(\n\t\tsum(\n\t\t\tcht_api_http_request_duration_seconds_count{instance=~\"$cht_instance\",route=~\".*/get-ids\",code=~\"^[45]..$\"} OR on() vector(0)\n\t\t)\n\t\t+ sum(\n\t\t\tcht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\",route=~\".*/get-ids\",ge=\"360.00\",code=~\"^2..$|^3..$\"} OR on() vector(0)\n\t\t)\n\t) / \n\tsum(\n\t\tcht_api_http_request_duration_seconds_count{instance=~\"$cht_instance\",route=~\".*/get-ids\"}\n\t)\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Replication Apdex",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n        (   \n                sum(increase(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\",route=~\".*/get-ids\",le=\"180.0\",code=~\"^2..$|^3..$\"}[$__range]))\n                + (\n                        sum(increase(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\",route=~\".*/get-ids\",le=\"360.0\",code=~\"^2..$|^3..$\"}[$__range]))\n                        - sum(increase(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\",route=~\".*/get-ids\",le=\"180.0\",code=~\"^2..$|^3..$\"}[$__range]))\n                ) / 2\n        ) / sum(increase(cht_api_http_request_duration_seconds_count{instance=~\"$cht_instance\",route=~\".*/get-ids\",code=~\"^2..$|^3..$\"}[$__range]))\n) * 100",
     "legendFormat": "score"
    }
   ]
  },
  {
   "title": "Replication Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\", route=~\".*/get-ids\"}[$interval])))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\", route=~\".*/get-ids\"}[$interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(1.00, sum by(le) (rate(cht_api_http_request_duration_seconds_bucket{instance=~\"$cht_instance\", route=~\".*/get-ids\"}[$interval])))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}