{
 "title": "CHT Admin Overview",
 "description": "Provides an overview of the CHT system metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cht_instance",
    "label": "CHT Instance",
    "query": {
     "query": "query_result(up{job=~\"cht\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "CHT Stack", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "# CHT Watchdog\n\nSee the [CHT documentation](https://docs.communityhealthtoolkit.org/apps/guides/hosting/monitoring/) for more information about monitoring and alerting!"
   }
  },
  {
   "title": "CHT Version Info",
   "type": "table",
   "description": "Software versions for the CHT stack",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "cht_version{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Growth Rate",
   "type": "timeseries",
   "description": "Rate of creation of docs in the Couch databases.",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "docs/hr" } },
   "targets": [
    {
     "expr": "rate(cht_couchdb_doc_total{instance=~\"$cht_instance\"}[1h]) * 60 * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHT Uptime",
   "type": "stat",
   "description": "How long API has been running.\n",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cht_date_uptime_seconds{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monthly Active Users",
   "type": "stat",
   "description": "Number of users that have connected to the api in the past month. ",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cht_connected_users_count{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Over Replication Limit",
   "type": "gauge",
   "description": "Number of users that exceeded the replication limit of documents.",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cht_replication_limit_count{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cht_connected_users_count{instance=~\"$cht_instance\"} * 0.003 + 2",
     "legendFormat": "users_threshold"
    }
   ]
  },
  {
   "title": "DB Conflicts Rate",
   "type": "stat",
   "description": "Rate of creation of doc conflicts which need to be resolved manually.",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "docs/day" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cht_conflict_count{instance=~\"$cht_instance\"}[24h]) * 60 * 60 * 24",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cht_couchdb_update_sequence{instance=~\"$cht_instance\", db=\"medic\"}[30d]) * 60 * 60 * 24 * 0.25 + 10",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "DB Fragmentation",
   "type": "bargauge",
   "description": "The fragmentation of the db, lower is better, “1” is no fragmentation.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cht_couchdb_fragmentation{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Time Accurate",
   "type": "stat",
   "description": "Indicates if the CHT server time matches the time of the Grafana server.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(abs(cht_date_current_millis{instance=~\"$cht_instance\"} / 1000 - time()))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound Push Backlog",
   "type": "gauge",
   "description": "Number of changes yet to be processed by Outbound Push.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cht_outbound_push_backlog_count{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cht_couchdb_update_sequence{db=\"medic\", instance=~\"$cht_instance\"}[30d]) * 60 * 60 * 0.05 + 5",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "Sentinel Backlog",
   "type": "gauge",
   "description": "Number of changes yet to be processed by Sentinel.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cht_sentinel_backlog_count{instance=~\"$cht_instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cht_couchdb_update_sequence{db=\"medic\", instance=~\"$cht_instance\"}[30d]) * 60 * 60 + 500",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "Couch2pg Backlog",
   "type": "gauge",
   "description": "Number of CouchDB changes that have not yet been processed by Couch2pg",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cht_couchdb_update_sequence{instance=~\"$cht_instance\", db=~\"medic|sentinel|medic-users-meta\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(couch2pg_progress_sequence{cht_instance=~\"$cht_instance\", db=~\"medic|medic-sentinel|medic-users-meta\"})",
     "legendFormat": "__auto"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Client Feedback/Error Rate",
   "type": "stat",
   "description": "Number of feedback docs created usually indicative of client side errors.",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "docs/day" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cht_feedback_total{instance=~\"$cht_instance\"}[24h]) * 60 * 60 * 24",
     "legendFormat": "__auto"
    },
    {
     "expr": "cht_connected_users_count{instance=~\"$cht_instance\"} / 10",
     "legendFormat": "threshold"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "description": "Alerts that need attention", "gridPos": { "h": 12, "w": 7, "x": 17, "y": 12 } },
  {
   "title": "Recent CHT Releases",
   "type": "table",
   "description": "Recent releases in the Community Healthcare Toolkit ecosystem",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "category": "All categories",
     "period": "monthly",
     "reportName": "topics_with_no_response.json",
     "searchArea": "topics_posts",
     "searchCategory": "releases",
     "searchSort": "latest",
     "userQuery": "topPublicUsers"
    }
   ]
  },
  {
   "title": "Message Delivery Rate [24h]",
   "type": "stat",
   "description": "The percentage of messages successfully delivered in the last 24hrs",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cht_messaging_outgoing_total{status=\"delivered\",instance=~\"$cht_instance\"}[24h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cht_messaging_outgoing_total{status=\"failed\",instance=~\"$cht_instance\"}[24h])",
     "legendFormat": "__auto"
    },
    { "expression": "$A/($A + $B)", "type": "math" }
   ]
  },
  {
   "title": "Monitoring Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus",
     "type": "stat",
     "description": "Indicates if Prometheus is up.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"prometheus\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Sample Rate",
     "type": "stat",
     "description": "Number of Prometheus samples collected in the last hour.",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "samples/hr" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{type=\"float\"}[1h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Skipped Scrapes [30d]",
     "type": "stat",
     "description": "Sum of all skipped Prometheus scrapes in the past 30 days",
     "gridPos": { "h": 4, "w": 4, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total[30d])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total[30d])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total[30d])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total[30d])) "
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "description": "How long it took to scrape a data source",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "scrape_duration_seconds{instance=\"$cht_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Prometheus Rejected Scrapes",
     "type": "timeseries",
     "description": "Total number of rejected scrapes in Prometheus",
     "gridPos": { "h": 6, "w": 9, "x": 4, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total)",
       "legendFormat": "exceeded sample limit"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total)",
       "legendFormat": "duplicate timestamp"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total)",
       "legendFormat": "out of bounds"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total) ",
       "legendFormat": "out of order"
      }
     ]
    },
    {
     "title": "JSON Exporter",
     "type": "stat",
     "description": "Indicates if the JSON Exporter (used for scraping CHT metrics) is up.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"json_exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}