{
 "title": "CHT Admin Details",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cht_instance",
    "label": "CHT Instance",
    "query": {
     "query": "query_result(up{job=~\"cht\"})"
    }
   },
   {
    "name": "db_name",
    "query": {
     "query": "cht_couchdb_doc_total{instance=~\"$cht_instance\"} >= 0"
    }
   }
  ]
 },
 "panels": [
  { "title": "CouchDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Doc Count [_users]",
   "type": "timeseries",
   "description": "Total number of docs in _users database",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cht_couchdb_doc_total{db=\"_users\", instance=~\"$cht_instance\"} >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Doc Count [medic]",
   "type": "timeseries",
   "description": "Total number of docs in medic database",
   "gridPos": { "h": 6, "w": 12, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "cht_couchdb_doc_total{db=\"medic\", instance=~\"$cht_instance\"} >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Doc Count [medic-users-meta]",
   "type": "timeseries",
   "description": "Total number of docs in medic-users-meta database",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cht_couchdb_doc_total{db=\"medic-users-meta\", instance=~\"$cht_instance\"} >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Doc Count [sentinel]",
   "type": "timeseries",
   "description": "Total number of docs in sentinel database",
   "gridPos": { "h": 6, "w": 12, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "cht_couchdb_doc_total{db=\"sentinel\", instance=~\"$cht_instance\"} >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Doc Conflicts",
   "type": "timeseries",
   "description": "Total number of doc conflicts which need to be resolved manually.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "cht_conflict_count{instance=~\"$cht_instance\"} >= 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(cht_couchdb_update_sequence{instance=~\"$cht_instance\", db=\"medic\"}[30d]) * 60 * 60 * 24 * 0.25 + 10",
     "legendFormat": "threshold"
    }
   ]
  },
  {
   "title": "Deleted Docs",
   "type": "timeseries",
   "description": "The number of deleted docs in the DB.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "cht_couchdb_doc_del_total{instance=~\"$cht_instance\"} >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Couch2pg Backlog",
   "type": "timeseries",
   "description": "Number of CouchDB changes that have not yet been processed by Couch2pg",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "cht_couchdb_update_sequence{instance=~\"$cht_instance\", db=~\"medic\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "couch2pg_progress_sequence{target=~\"$cht_instance\", db=~\"medic\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$A - $B", "reducer": "mean", "type": "math" },
    {
     "expr": "cht_couchdb_update_sequence{instance=~\"$cht_instance\", db=~\"medic-users-meta\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "couch2pg_progress_sequence{target=~\"$cht_instance\", db=~\"medic-users-meta\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$C - $D", "type": "math" },
    {
     "expr": "cht_couchdb_update_sequence{instance=~\"$cht_instance\", db=~\"sentinel\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "couch2pg_progress_sequence{target=~\"$cht_instance\", db=~\"medic-sentinel\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$E - $F", "type": "math" }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "timeseries",
   "description": "The fragmentation of the db, lower is better, “1” is no fragmentation.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "cht_couchdb_fragmentation{instance=~\"$cht_instance\"} >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CHT Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Server Time",
     "type": "stat",
     "description": "The current server date and time, useful for ensuring the server time is correct.",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_date_current_millis{instance=~\"$cht_instance\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sentinel Backlog",
     "type": "timeseries",
     "description": "Number of changes yet to be processed by Sentinel.",
     "gridPos": { "h": 6, "w": 10, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "changes" } },
     "targets": [
      {
       "expr": "cht_sentinel_backlog_count{instance=~\"$cht_instance\"} >= 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(cht_couchdb_update_sequence{db=\"medic\", instance=~\"$cht_instance\"}[30d]) * 60 * 60 + 500",
       "legendFormat": "threshold"
      }
     ]
    },
    {
     "title": "Users Over Replication Limit",
     "type": "timeseries",
     "description": "Number of users that exceeded the replication limit of documents.",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "users" } },
     "targets": [
      {
       "expr": "cht_replication_limit_count{instance=~\"$cht_instance\"} >= 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "cht_connected_users_count{instance=~\"$cht_instance\"} * 0.003 + 2",
       "legendFormat": "users_threshold"
      }
     ]
    },
    {
     "title": "Client Feedback/Errors",
     "type": "timeseries",
     "description": "Number of feedback docs created usually indicative of client side errors.",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "cht_feedback_total{instance=~\"$cht_instance\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound Push Backlog",
     "type": "timeseries",
     "description": "Number of changes yet to be processed by Outbound Push.",
     "gridPos": { "h": 6, "w": 10, "x": 5, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "changes" } },
     "targets": [
      {
       "expr": "cht_outbound_push_backlog_count{instance=~\"$cht_instance\"} >= 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(cht_couchdb_update_sequence{db=\"medic\", instance=~\"$cht_instance\"}[30d]) * 60 * 60 * 0.05 + 5",
       "legendFormat": "threshold"
      }
     ]
    },
    {
     "title": "Monthly Active Users",
     "type": "timeseries",
     "description": "Number of users that have connected to the api in the past month.",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "users" } },
     "targets": [
      {
       "expr": "cht_connected_users_count{instance=~\"$cht_instance\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(cht_messaging_outgoing_total{instance=~\"$cht_instance\"}) >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Due",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 11, "y": 11 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"due\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Delivered",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 11 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"delivered\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Muted",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 11, "y": 15 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"muted\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 15 },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_total{instance=~\"$cht_instance\", status=\"failed\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Messages - Last 100",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"} >= 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"} >= 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"} >= 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 7, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Muted",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 13, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Final",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 7, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 13, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"} >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"pending\"} >= 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"muted\"} >= 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(cht_messaging_outgoing_last_hundred{instance=~\"$cht_instance\", group=\"final\"} >= 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}