{
 "title": "UMT Server",
 "description": "Monitor metrics for UMT node.js",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "umt_instance",
    "label": "UMT Instance",
    "query": {
     "query": "query_result(up{job=~\"cht-user-management-metrics\"})"
    }
   },
   {
    "name": "interval",
    "query": "2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$umt_instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{instance=~\"$umt_instance\"})"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\tsum(\n\t\thttp_request_duration_seconds_count{instance=~\"$umt_instance\",code=~\"^[45]..$\"} OR on() vector(0)\n\t) / \n\tsum(\n\t\thttp_request_duration_seconds_count{instance=~\"$umt_instance\"}\n\t)\n)*100",
     "legendFormat": "error %"
    }
   ]
  },
  {
   "title": "Transferred",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes_sum{instance=~\"$umt_instance\"}) + sum(http_request_size_bytes_sum{instance=~\"$umt_instance\"})"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_response_size_bytes_sum{instance=~\"$umt_instance\"}[$interval])) + sum(rate(http_request_size_bytes_sum{instance=~\"$umt_instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Restarts in 7d",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$umt_instance\"}[7d]))"
    }
   ]
  },
  {
   "title": "Node.js Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Eventloop Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$umt_instance\"}",
     "legendFormat": "last"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{instance=~\"$umt_instance\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{instance=~\"$umt_instance\"}",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Rate of CPU Time Spent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$umt_instance\"}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$umt_instance\"}",
     "legendFormat": "virtual memory"
    },
    {
     "expr": "process_heap_bytes{instance=~\"$umt_instance\"}",
     "legendFormat": "heap memory"
    }
   ]
  },
  {
   "title": "Number of Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "expressjs_number_of_open_connections{instance=~\"$umt_instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "( process_open_fds{instance=~\"$umt_instance\"} / process_max_fds{instance=~\"$umt_instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$umt_instance\"}",
     "legendFormat": "Active Handler"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$umt_instance\"}",
     "legendFormat": "Active Request"
    }
   ]
  },
  {
   "title": "Node.js Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{instance=~\"$umt_instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{instance=~\"$umt_instance\"}[$interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{instance=~\"$umt_instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{instance=~\"$umt_instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$umt_instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$umt_instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$umt_instance\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$umt_instance\"}",
     "legendFormat": "external"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$umt_instance\"}",
     "legendFormat": "{{space}}"
    }
   ]
  },
  {
   "title": "Express Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Per Seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{instance=~\"$umt_instance\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Response Latency (90th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{instance=~\"$umt_instance\"}[$interval])) by (le,route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Code Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{instance=~\"$umt_instance\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes_sum{instance=~\"$umt_instance\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{instance=~\"$umt_instance\"}) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, sum by (route)(http_request_duration_seconds_sum{instance=~\"$umt_instance\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, sum by (route)(http_request_duration_seconds_sum{instance=~\"$umt_instance\",code=~\"^[23]..$\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Duration",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, sum by (route)(http_request_duration_seconds_sum{instance=~\"$umt_instance\",code=~\"^[45]..$\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 5 Request Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum by (route)(http_request_duration_seconds_count{instance=~\"$umt_instance\"}))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Top 5 Success Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, http_request_duration_seconds_count{instance=~\"$umt_instance\",code=~\"^[23]..$\"})",
     "legendFormat": "({{code}}) {{route}}"
    }
   ]
  },
  {
   "title": "Top 5 Error Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, http_request_duration_seconds_count{instance=~\"$umt_instance\",code=~\"^[45]..$\"})",
     "legendFormat": "({{code}}) {{route}}"
    }
   ]
  }
 ]
}